[tool.poetry]
name = "nca"
version = "0.1.0"
description = ""
authors = ["Iliya Zhechev <iliya.zhechev@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
matplotlib = "^3.5.2"
numpy = "^1.22.4"
jupyter = "^1.0.0"
ipdb = "^0.13.9"
tqdm = "^4.64.0"
moviepy = "^1.0.3"
scipy = "^1.10.1"
termcolor = "^2.2.0"
torch = "^2.2.0"
torchvision = "^0.17.0"
kornia = "^0.7.1"
lightning = "^2.2.5"
tensorboard = "^2.16.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.6.0"
black = { version = "^22.3.0", allow-prereleases = true }

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
